[project]
name = "peak-time"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.17.0",
    "litestar[standard]>=2.14.0",
    "sqlalchemy>=2.0.38",
]
