[project]
name = "peak-time"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "advanced-alchemy>=0.30.3",
    "aiogram>=3.17.0",
    "aiosqlite>=0.21.0",
    "litestar[standard]>=2.14.0",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.38",
]
